=== horstoeko/zugferdmail/src/config/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": [
        "dateFormat",
        "ublSupportEnabled",
        "symfonyValidationEnabled",
        "xsdValidationEnabled",
        "kositValidationEnabled",
        "accounts"
    ],
    "properties": {
        "dateFormat": {
            "type": "string"
        },
        "ublSupportEnabled": {
            "type": "boolean"
        },
        "symfonyValidationEnabled": {
            "type": "boolean"
        },
        "xsdValidationEnabled": {
            "type": "boolean"
        },
        "kositValidationEnabled": {
            "type": "boolean"
        },
        "accounts": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "identifier",
                    "host",
                    "port",
                    "protocol",
                    "encryption",
                    "validateCert",
                    "username",
                    "password",
                    "authentication",
                    "timeout",
                    "foldersToWatch",
                    "mimeTypesToWatch",
                    "handlers"
                ],
                "properties": {
                    "identifier": {
                        "type": "string"
                    },
                    "host": {
                        "type": "string"
                    },
                    "port": {
                        "type": "integer",
                        "minimum": 0,
                        "maximu,": 65535
                    },
                    "protocol": {
                        "type": "string",
                        "oneOf": [
                            {
                                "const": "imap"
                            },
                            {
                                "const": "legacy-imap"
                            },
                            {
                                "const": "pop3"
                            },
                            {
                                "const": "nntp"
                            }
                        ]
                    },
                    "encryption": {
                        "type": [
                            "string",
                            "boolean"
                        ],
                        "oneOf": [
                            {
                                "const": false
                            },
                            {
                                "const": "ssl"
                            },
                            {
                                "const": "tls"
                            },
                            {
                                "const": "starttls"
                            },
                            {
                                "const": "notls"
                            }
                        ]
                    },
                    "validateCert": {
                        "type": "boolean"
                    },
                    "username": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "authentication": {
                        "type": [
                            "string",
                            "null"
                        ],
                        "oneOf": [
                            {
                                "const": null
                            },
                            {
                                "const": "oauth"
                            }
                        ]
                    },
                    "timeout": {
                        "type": "integer"
                    },
                    "foldersToWatch": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "mimeTypesToWatch": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "handlers": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "classname": {
                                    "type": "string"
                                },
                                "properties": {
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== horstoeko/zugferdmail/tests/assets/config.save.json
{
    "dateFormat": "d-M-Y",
    "ublSupportEnabled": false,
    "symfonyValidationEnabled": true,
    "xsdValidationEnabled": true,
    "kositValidationEnabled": true,
    "accounts": [
        {
            "identifier": "3ACD7956-A9BB-427B-A0C6-0F347A485D74",
            "host": "127.0.0.1",
            "port": 993,
            "protocol": "imap",
            "encryption": "tls",
            "validateCert": true,
            "username": "demouser",
            "password": "demopassword",
            "authentication": null,
            "timeout": 30,
            "foldersToWatch": [
                "INBOX",
                "INBOX\/somefolder"
            ],
            "mimeTypesToWatch": [
                "text\/xml",
                "application\/pdf"
            ],
            "handlers": [
                {
                    "classname": "horstoeko\\zugferdmail\\handlers\\ZugferdMailHandlerNull",
                    "properties": {}
                },
                {
                    "classname": "horstoeko\\zugferdmail\\handlers\\ZugferdMailHandlerCopyMessage",
                    "properties": {
                        "copyToFolder": "INBOX\/someotherfolder"
                    }
                }
            ]
        }
    ]
}
